[RO] Add ''Twitter''
osu-ro/osu-wiki pull request #2
Opened 2022-08-07 16:27 UTC by 0xDaniel

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-07 17:59 UTC, NiceAesth requested changes

2022-08-07 17:59 UTC, NiceAesth commented on wiki/Twitter/ro.md
> +osu! are mai multe conturi de Twitter, fiecare având scopuri specifice. Cele mai multe au un trafic foarte redus, dar vă vor ajuta să vă țineți la curent în afara ecosistemului osu!
```suggestion
osu! are mai multe conturi de Twitter, fiecare având scopuri particulare. Majoritatea au un flux redus de postări, dar vă vor ajuta să vă țineți la curent în afara ecosistemului osu!
```

2022-08-07 17:59 UTC, NiceAesth commented on wiki/Twitter/ro.md
> +## Comunitare
```suggestion
## Comunitate
```

2022-08-07 17:59 UTC, NiceAesth commented on wiki/Twitter/ro.md
> +## Personal
```suggestion
## Personale
```
Se referă la "conturile" personale, chiar dacă în tabel e unul singur

2022-08-07 17:59 UTC, NiceAesth commented on wiki/Twitter/ro.md
> +| ![Dean Herbert avatar](img/ppy.jpg) | [@ppy](https://twitter.com/ppy) | Contul personal de Twitter al [creatorului osu!](/wiki/People/peppy), care nu este strict legat de osu!, dar care acoperă o m
nu sunt fan al repetiției cuvântului care. aștept sugestii

2022-08-12 17:50 UTC, NiceAesth commented on wiki/Twitter/ro.md
> +| ![BanchoBoat avatar](img/banchoboat.jpg) | [@banchoboat](https://twitter.com/banchoboat) | Comedy relief when things go wrong. |
```suggestion
| ![BanchoBoat avatar](img/banchoboat.jpg) | [@banchoboat](https://twitter.com/banchoboat) | Postări comice când lucrurile eșuează. |
```

2023-01-21 16:52 UTC, NiceAesth approved these changes

2023-01-21 16:56 UTC, entwastaken approved these changes

2023-01-21 16:56 UTC, merged